version: '3'

services:
  db:
    image: postgres:9.5
  web:
    build: .
    command: rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/womenrising
    ports:
      - "3000:3000"
    depends_on:
      - db
